#define PACKAGE_NAME "vkd3d"
#define PACKAGE_STRING "vkd3d 1.12"
#define PACKAGE_VERSION "1.12"
#define PATH_MAX 1024
#define SONAME_LIBVULKAN "vulkan-1.dll"

#define HAVE_SPIRV_UNIFIED1_SPIRV_H
#define HAVE_SPIRV_UNIFIED1_GLSL_STD_450_H
